= pasberth.github.io/diary
:toc:

== 2014-01-01

Eliom のチュートリアルを一通り読んだ．コピペして試した．

. http://ocsigen.org/tutorial/intro[Introduction ]
. http://ocsigen.org/tutorial/application[Writing a client/server Eliom application ]
. http://ocsigen.org/tutorial/interaction[Implementing Web Interaction Using Eliom ]

英語が読めなくて完全に苦痛だった．
すこしは勉強しているので，1割くらいの英文は読めた．
単語が完全にわからなかった．英文法は7割くらいわかったけど単語がまったくわからない．
単語を勉強する必要あり．

http://www.ookamikodomo.jp/index.html[おおかみこどもの雨と雪 ] を視聴した．13回目．

どんな小さなことも記録しようと心に決め，このダイアリをつくった．
今日は1日め．来年は進捗カレンダーをつくれるように頑張る．




== 2014-01-02

おおかみこどもの雨と雪の原作小説を読んだ．
とても読みやすい小説だった．映像版を先に見たからかもしれない．
ただ，語り部の視点が何度もころころと変わるのと，主語の省略が気にかかった．
その物語は，主に，花と，雪と，雨の視点で描かれるのだけど，場面ごとに誰の主観で書かれた
文章なのかが変わった．混乱する事はなく，むしろかなりうまく切り替えられていると感じたが，
「ぼくならこうは書かないな」と思った．主語の省略は，たびたびぼくに混乱をもたらした．
ぼくは段落を変えた直後に主語を省略してはいけないと思う．段落が変わったにも関わらず，
主語が省略されていると，誰の視点なのかわからなくなってしまうと感じた．

いとこ(小学3年生)に絵本と言って Land of Lisp をあげた．
すこし遅れたものの，元日だからだ．

みんながいい本だと言っていたので，リーダブルコードと，
最新コンパイラ構成技法(タイガーブック)と，
ストラウストラップのプログラミング入門を買った．積読がまた3つ増えた．
リーダブルコードは比較的すぐ読めそうなので読もうと思う．

//FIXME
//:doc:`/blog/entry/2014-01-02/index` を書き，そのブログに書いてある事をした．

http://mzp.hatenablog.com/entry/2013/06/08/003029[2013-06-08 OCamlで作ったWebアプリをHerokuで動かす方法(2) 〜Ocsigen/Eliom編〜  ]
と http://ocsigen.org/tutorial/macaque[Type safe database requests using Macaque ] を
読んだ． Macaque という OCaml 製の O/R Mapper (って言うのか?) があるらしい．
どうやら内包表記っぽく SQL にアクセスできるようだ．
じっさい SQL は集合指向なんて言われる事もあるし内包表記はかなりわかりやすい．

Eliom で書かれた https://github.com/heroku-buildpack-ocaml/sample-todo-app[heroku-buildpack-ocaml/sample-todo-app ]
を clone して動かそうと思ったけど動かなかった．考えてみれば，環境変数とかデータベースとか用意して
ないし当たり前だ．どんな環境変数やデータベースを用意すれば動かせるのかわからなかったので，試すのは
諦めた．その代わりザッとコードを眺めた．

それから日付が変わった．いまは 2014年1月3日0時4分だ．今日はもう寝ようと思う．


== 2014-01-03

読書の習慣をつけようと思った．正直今までは読書する習慣がなかった．
積読も溜まっている．いけないことだ．どんどん読んでいかないと消化しきれない．
1日に1冊は読もうと思った．ジャンルは小説でもいいし技術書でもいい．

まずはじめに，リーダブルコードを読んだ．
いろいろと思うところはあったけど全体として良書だった．感想は :doc:`/blog/entry/2014-01-03/index`
に書いた．

おおかみこどもの雨と雪を視聴した．通算16回め．

1日1回絵を描くと言っていたのにずいぶんサボっていたので，絵を描いた．
おおかみおとこ．苦痛だった．描きたくなかった．

//FIXME
//.. figure:: a.png
//    :width: 600px

リーダブルコードを読んだので，けっきょく 200ページ 以上読んだ事になる．
100 ページくらい読んだ頃から，かなり集中力が失われていた．どうにか読み切ったけど，
疲れてしまってそのほかのことはほとんどできなかった．1日にできる進捗は
高々 100 ページ読むくらいなのかもしれない．この分だとストラウストラップの
プログラミング入門や最新コンパイラ構成法をぜんぶ読むのにはどう少なく見積もっても
1ヶ月はかかる．読みたい本の量はぼくのもっている時間を凌駕している．時間が足りない．
去年ダラダラしていたのがマジで恨めしい．

本を読むのは大事だと完全に理解した．去年は言語とかつくろうと思ってたけど，
ダメだ．完全に理解した．ぼくにはプログラミング言語を実装できるだけの実力はない．
本を読むのに徹しないとダメだ．それどころか，ブログを書く能力すらボクにはない．
なにかをつくりだすとか，なにかを主張するのはマジで控えたほうがいいと思った．
それはたぶん，稚拙だ．できるのは日記を書くくらいだ．日記を書くのは大事だと
完全に理解した．たとえ散文でも，意味不明な文章でも，記録をつけるのは大事だ．
記録しないとすぐに忘れてしまう．そういうのは private でやるべきな気はする
んだけど，正直公開してツイッタアに流さないと承認欲求満たされなくてモチベ
死ぬし，実利的な意味でも Dropbox で管理するよりは GitHub で管理して
ブラウザさえあればどこからでも見れるほうが便利だと思うので公開にしておく．

ストラウストラップのプログラミングの最初のほうだけ読んだ．
完全に実用的な言語の話をしていた． C++ にちょっと興味をもった．
読んでいて，じっさい LISP や OCaml が良い言語だといえど，
*実用的な言語の話をしている* を感じた気がした．

目次を読んで，22章 *理想と歴史* にとても興味をもった．タイトルを読んだだけでも
はやく読みたいとワクワクした．先に読んでもいいかもしれない．
アブストを読んだだけで完全に良書だと完璧に理解した．
タイトルの通り，プログラミング入門っぽい．読み追えたら，
プログラミングしたことない人が最初に読むべき本として布教しているかもしれない
と思った．

これから眠るまでストラウストラップのプログラミング入門を読もうと思う．
たぶんうとうとしてくる．そしたら寝る．

== 2014-01-04

ストラウストラップのプログラミング入門をだいたい100ページくらい
読んだ．最初の方は本当に基礎的な内容なのでスイスイ読めた．第5章を前に休憩した．
ちゃんと計ったわけではないけど，たぶん，読むのにかかった時間は6時間くらいだ．

リーダブルコードを読んだときは，1日に200ページ読んだ．内容は無視したとして，今日は半分しか
読めなかったことになる．ストラウストラップのプログラミング入門は1000ページ以上あって，
どうせ1日では読み切れないから日をまたぐ事になるという諦めがぼくを怠けさせた．
明日は300ページは読むべきだ．単純に計算すると，そのままのペースで読めば1週間くらい
で読み終える．

たぶん3時間以上はツイッターしてた．6時間くらいツイッターしてたかもしれない．
1日のうち，たぶん半分くらいはツイッターしてるんじゃなかろうかと思った．時間の
ムダだ．

おおかみこどもの雨と雪を視聴した．通算20回め．

//FIXME
//知り合いが Haskell を勉強したいと言っていたので，ぼくも協力すべく，たぶん3時間くらいは
//:download:`brief-intro-haskell-language.pdf <brief-intro-haskell-language.pdf>`
//を製作するのに費やした．けっきょく完成しなかったというか，つくるだけ無意味だと
//思ったのでやめた． Haskell を勉強するならすでにもっといい文献がたくさんあるし，
//ぼくは教科書を書くだけの知識を備えていない．

//あと，21時頃の話なんだけど，

//.. raw:: html
//
//    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
//    <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
//    <blockquote class="twitter-tweet" lang="ja"><p>パスベルスさん、最初見た時はまともな人だと思っていたけど、どんどん関わるとマズい人になっていってる様な気がする。</p>&mdash; marionette-of-u (@uwanosolambda) <a href="https://twitter.com/uwanosolambda/statuses/419443073668493313">2014, 1月 4</a></blockquote>
//    <blockquote class="twitter-tweet" lang="ja"><p>ぱすべるす氏はなんか最初のうちは普通のプログラムガチ勢な感じだったのに最近は文体がネタツイッタラーに</p>&mdash; はる(Unstable) (@haru2036) <a href="https://twitter.com/haru2036/statuses/419443602754764800">2014, 1月 4</a></blockquote>
//    <blockquote class="twitter-tweet" lang="ja"><p>Ekmett勉強会頃のパスベルスはもちょいマトモだったのにな。</p>&mdash; ちゅーん (@its_out_of_tune) <a href="https://twitter.com/its_out_of_tune/statuses/419443590767448064">2014, 1月 4</a></blockquote>

//とのこと．載せようか迷ったんだけど，日記だし載せる事にした．
//わりと自分を冷静に見れていなかった節がある．反省する．

== 2014-01-05

今日は9時15分頃に起きて，10時27分頃まではダラダラしていた．
それから12時17分頃まではおおかみこどもの雨と雪を見ながら，
ストラウストラップのプログラミング入門の5章を読んでいた．
それから1時54分頃までは https://github.com/ruby/ruby/blob/trunk/bignum.c[bignum.c ]
を読みながらダラダラしていた．それから13時17分頃までツイッタアしてダラダラしていた．反省．

ストラウストラップのプログラミング入門で印象に残った言葉がいくつかあった．
以下は列挙．

* *エラーの回避、検出、修正には、本格的なソフトウェアを開発する労力の90%以上が
  費やされている*  (p105)

* *完成させることが不可能なプロジェクトを始めたところで、ほとんど無意味である* (p144)

* *「乗算は加算よりも優先される」なんてばかげた古くさい決まりだと思っているかもしれないが、
  数百年も続いている決まりがプログラミングを単純にするためになくなることはない* (p148)

* *プログラミングにおいて最も手のかかる問題は、多くの場合、私たちがコンピュータを使い始める
  ずっと以前から続く人間の慣習的なルールとつじつまを合わせなければならないときに発生する* (p165)

良いプログラムはそのほとんどがエラー処理に費やされているものらしい．

髪を切って，ラーメンを食べた．そのあと，カイジ2を見た．
面白かった(小学生並みの感想)．

ストラウストラップのプログラミング入門を9章まで読み終えた．
約200ページくらい読んだ．残り700ページくらい．
1/3は読み終えたと思う．あと3日もあればぜんぶ読めそうだ．

//:doc:`/blog/entry/2014-01-05/index` を書いた．

== 2014-01-06

進捗ダメです．

http://www.ee.t-kougei.ac.jp/tuushin/inside/multiplePrecision/memo.pdf[memo.pdf ]
を見ながら https://github.com/pasberth/numbers[github.com/pasberth/numbers ] を
つくった．任意精度整数．メモリリークしてる．つらいwwっ


== 2014-01-07

今日はまったく進捗しなかった．

https://github.com/pasberth/numbers[github.com/pasberth/numbers ] を
メモリリークしないように直した． http://kt3k.github.io/d3intro/[about D3.js ]
を見て D3.js スゲェっつった．

メモ:

* https://www.lri.fr/~filliatr/ftp/publis/spds-rr.pdf[spds-rr.pdf ]
* http://www.cs.cmu.edu/~donna/public/malayeri.fool07.pdf[malayeri.fool07.pdf ]

意味がわからなかった．

http://faithandbrave.hateblo.jp/entry/2014/01/07/161821[これ ] 見て
ヤベェっつった．ムダに http://ja.wikipedia.org/wiki/%E3%82%A2%E3%83%96%E3%83%89%E3%82%A5%E3%83%83%E3%83%A9%E3%83%BC2%E4%B8%96[ここ ]
とか見てた．

http://www.infoq.com/jp/news/2014/01/mirageos[Xen Project，Mirage 0S 1.0をリリース ] を
見て Mirage OS ヤベェっつった．

つらいwwっ．寝る．

== 2014-01-08

今日はまったく進捗しなかった．

https://github.com/pasberth/numbers[pasberth/numbers ] に減算を実装した．
link:http://ezoeryou.github.io/cpp-book/C++11-Syntax-and-Feature.xhtml[C++11-Syntax-and-Feature.xhtml ]
を読んだ．

メモ:

* http://www.cs.cmu.edu/~rwh/theses/okasaki.pdf[okasaki.pdf ]

あとはなにしたか忘れた．
マジで，1日どころか1時間とかのレベルでメモしないとなにしたか完全に忘れる．
ヤバい．

== 2014-01-09

今日はまったく進捗しなかった．

メモ:

* http://www.nue.riec.tohoku.ac.jp/lab-intro/TRS-intro/#trs[項書き換えシステムの例 ]

読みたい:

* http://www.slideshare.net/tokibito/hadoop-29808502[hadoop-29808502 ]
* http://www.cs.cmu.edu/~rwh/theses/okasaki.pdf[okasaki.pdf ]

意味がわかりません＾＾；

* http://www.blackhat.com/presentations/bh-dc-07/Sabanal_Yason/Paper/bh-dc-07-Sabanal_Yason-WP.pdf[Reversing C++ ]


ハハハ，こやつめ:

* http://hatsunetsu7.hatenablog.com/entry/2014/01/08/230939[Prolog on Prolog on Lisp ]

＾＾；

* https://speakerdeck.com/ntddk/using-llvm-for-malware-deobfuscation[Using LLVM for malware deobfuscation ]

ヤバい:

* https://github.com/Constellation/esmangle[esmangle ]
* https://github.com/ariya/esprima[esprima ]
* https://github.com/Constellation/escodegen[escodegen ]

https://gist.github.com/pasberth/8335035[進捗 ]

== 2014-01-11

先日は日記を書くのを怠ってしまった．
反省．しかも，昨日なにしていたのか完全に思い出せない．
なにかしていたのかもしれないが，なにもしていなかったのかもしれない．
日記を書くのは大事だ．完全に理解した．

今日はラムダリスと遊んでいて進捗しなかった．
C# の async / await という機能がいいらしい．
あと Rx も．それを試したりしていた．

ラムダリスにタイガーブックを勧めた．
逆に，ぼくは HACKING: 美しき策謀 を勧められたので買った．

そういえば，入門 自然言語処理が名著らしい． 
(http://coreblog.org/ats/ten-reasons-why-analyzing-text-with-the-nltp-should-be-a-prohibited-book/[ソース ])
わずか2日前の事なのに，もう忘れかけていた．メモメモ．

絵を1枚描いた．
たぶん，ほとんどの時間をツイッターで過ごした…．
あとは寝る．

== 2014-01-12

ストラウストラップのプログラミング入門を読破した．

次は入門データ構造とアルゴリズムを読もうとしている．

みょんさんの http://myuon.digi2.jp/pictures.html[ここにおいてる指をくるくるまわすGIF ]
にひどく感動して，今日は 1日じゅう次のような GIF をつくっていた．

.. figure:: kurukuru.gif
    :width: 600px

それなりに可愛いと思う． 色もつけたい． しかし，服を描いているところで Painter
がクラッシュして モチベーションを完全に失った． 今日は寝る．

== 2014-01-13

これをつくってた．

.. figure:: kurukuru.gif
    :width: 600px

:doc:`/gallery/kurukuru/index` においてある．
他のことは一切してない．
寝る．


== 2014-01-14

O表記を完全に理解した．
**スター・トレック イントゥ ダークネス** を視聴した．
他にはなにもしてない

== 2014-01-15

CDを8買った．

== 2014-01-16

英語の勉強をちょっと進めた

== 2014-01-17

英語リーディング教本読了．

== 2014-01-18

(英語の)本を読んでも，単語が全然わからない．
文法はわかるようになってきた．
単語力を高めるため，中学・高校6年分の英単語を総復習するを買ってきた．
今日は20語ほど新しい単語を覚えた．
どれもこれも中学レベルの単語なのでマジでヤバい．

== 2014-01-19

単語の勉強ちょっと進めた．
もうちょっとペースあげないとヤバい．

絵を2枚描いた．

.. figure:: d.png
    :width: 600px

.. figure:: fr.png
    :width: 600px

自分は継続することができない人間なのだなぁと実感する．
とりあえず日記は1年続けよう．

絵を描くのも，1日1枚描くと言いながら，かなりサボり気味だ．
12月23日くらいから， :doc:`/diary/entry/2014-01-03/index` くらいまで
の間描いてなかった． :doc:`/diary/entry/2014-01-03/index` から数えて，
今日までで合計10枚くらい描いていたらしい．
ペースとしてはいい感じか？
絵を描くのも，ラクガキくらいなら毎日できるはずだ．
継続する力が必要だ．これも続けよう．


== 2014-01-20

単語の勉強ちょっと進めた．

良さげかも: http://mustache.github.io/[mustache ]

読んだ: http://www.tatapa.org/~takuo/structured_programming/structured_programming.html[意外と知られていない構造化プログラミング、あるいは構造化プログラミングはデータも手続きと一緒に抽象化する、あるいはストロヴストルップのオブジェクト指向プログラミング史観 ]

…: http://nekogata.hatenablog.com/entry/2014/01/17/125600[猫型プログラミング言語史観(1) 〜あるいはオブジェクト指向における設計指針のひとつ〜 ]

興味深い: http://www.tatapa.org/~takuo/cs_paper/cs_paper_2011.html#what_is_object-oriented_programming[2011年に読んだ論文紹介 または私は如何にして心配するのを止めて静的に型付けされたオブジェクト指向言語を愛するようになったか ]

あとで読みたい: http://www.sampou.org/haskell/report-revised-j/decls.html[4  宣言と束縛 ]
とくに **4.5  関数束縛およびパターン束縛の 静的セマンティクス** は読まないとダメっぽい．

Note: *単相性制限*

== 2014-01-21

進捗ダメです．

絵を1枚描いた．

.. figure:: pasberth_pants.png
    :width: 600px

興味深い:

* http://www.slideshare.net/suzaki/os-30235081[チュートリアル 2014/Jan/8 OS周りのセキュリティ対策 ]
* http://shell-storm.org/project/ROPgadget/[ROPgadget - Gadgets finder and auto-roper ]
* http://www.vnsecurity.net/2010/08/ropeme-rop-exploit-made-easy/[ROPEME – ROP Exploit Made Easy ]

＾＾； :

* http://d.hatena.ne.jp/boleros/20130318/1363630130[USBメモリを「USB」と略す人間らは腹を切って死ぬべきである。また、USBメモリを「USB」と略す人間らはただ死んで終わるものではない。彼らは無責任な悪人であり、中３女子が地獄の火の中に投げ込む者達である。 ]

メモ:

* http://ja.wikipedia.org/wiki/%E6%8F%9B%E5%96%A9[換喩 ]
* http://ja.wikipedia.org/wiki/%E6%8F%90%E5%96%A9[提喩 ]

読みたい！！！！！！:

* http://www.amazon.co.jp/%E8%A8%98%E5%8F%B7%E3%81%A8%E5%86%8D%E5%B8%B0-%E8%A8%98%E5%8F%B7%E8%AB%96%E3%81%AE%E5%BD%A2%E5%BC%8F%E3%83%BB%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%A0%E3%81%AE%E5%BF%85%E7%84%B6-%E7%94%B0%E4%B8%AD-%E4%B9%85%E7%BE%8E%E5%AD%90/dp/4130802518[記号と再帰: 記号論の形式・プログラムの必然 ]

== 2014-01-22

英単語をけっこう覚えた．そこそこの進捗だった．

絵を1枚描いた．

.. figure:: a.png
    :width: 600px


== 2014-01-23

.. raw:: html

    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
    <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

進捗ダメです．

.. raw:: html

    <blockquote class="twitter-tweet" lang="ja"><p>塗ってもいいのよ線画 <a href="http://t.co/x2OCjGiG5M">http://t.co/x2OCjGiG5M</a></p>&mdash; あいこ (@Aiko3dayo) <a href="https://twitter.com/Aiko3dayo/statuses/426314968556765185">2014, 1月 23</a></blockquote>

というわけで塗った．

.. raw:: html

    <blockquote class="twitter-tweet" lang="ja"><p><a href="https://twitter.com/Aiko3dayo">@Aiko3dayo</a> <a href="http://t.co/vTEyRgxGVC">http://t.co/vTEyRgxGVC</a> 塗ってみました</p>&mdash; パスベルス (@pasberth) <a href="https://twitter.com/pasberth/statuses/426337271638278144">2014, 1月 23</a></blockquote>

絵を1枚描いた．

.. figure:: a.png
    :width: 600px

興味深い:

* http://www.vpri.org/pdf/tr2007002_packrat.pdf[tr2007002_packrat.pdf ]
* http://open-std.org/jtc1/sc22/wg21/docs/papers/2014/n3843.pdf[n3843.pdf ]
* http://www.amazon.co.jp/gp/product/4621061224?ie=UTF8&camp=1207&creative=8411&creativeASIN=4621061224&linkCode=shr&tag=chosser-22[パターン認識と機械学習 上 ]
* http://www.youtube.com/watch?v=0-vWT-t0UHg[The 67th Yokohama kernel reading party  ]
* http://www.slideshare.net/kosaki55tea/glibc-malloc[malloc の旅 ]
* http://raml.org/[RAML ]

== 2014-01-24

英単語をけっこう覚えた．そこそこの進捗だった．

ルドヴィカを描いた．

.. figure:: ludovika.png
    :width: 600px

ちなみに線画もある． MIT ライセンスです．
自由に塗り絵してください．

.. figure:: ludovika_senga.png
    :width: 600px


== 2014-01-28

興味深い:

* http://www.cse.chalmers.se/~mortberg/talks/progloghomology2011.pdf[Homology of simplicial complexes in HaskelL ]
* http://www.amazon.co.jp/Finite-Automata-Mark-V-Lawson/dp/1584882557/ref=sr_1_sc_1?ie=UTF8&qid=1390679863&sr=8-1-spell&keywords=lawson+finite+autoamta[Finite Automata ]
* http://www.proofwiki.org/wiki/Peirce%27s_Law_Equivalent_to_Law_of_Excluded_Middle[Peirce's Law Equivalent to Law of Excluded Middle ]
* http://www.kmonos.net/pub/Presen/HiC.pdf[Towards High-Order Syntax of C Programming Language ]
* http://cpplover.blogspot.jp/2014/01/clang-vs.html[Clang VS 自由ソフトウェア  ]
* http://bleis-tift.hatenablog.com/entry/computation-expression[コンピュテーション式とは ]
* http://www.amazon.co.jp/%E3%82%B8%E3%82%A7%E3%83%8D%E3%83%AC%E3%83%BC%E3%83%86%E3%82%A3%E3%83%96%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%9F%E3%83%B3%E3%82%B0-IT-Architects%E2%80%99Archive-CLASSIC-MODER/dp/479811331X[ジェネレーティブプログラミング ]


== 2014-01-29

:doc:`/gallery/mephi/index` を描いた

== 2014-01-31

:doc:`/gallery/yuri/index` を描いた

== 2014-02-01

:doc:`/gallery/yuri2/index` を描いた

== 2014-02-02

.. raw:: html

    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
    <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
    <blockquote class="twitter-tweet" lang="ja"><p><a href="http://t.co/MXDFOq2y7F">http://t.co/MXDFOq2y7F</a> 漫画を描きました</p>&mdash; パスベルス (@pasberth) <a href="https://twitter.com/pasberth/statuses/429951044336902144">2014, 2月 2</a></blockquote>


== 2014-02-03

マグダラで眠れ2読了

== 2014-02-04

https://github.com/pasberth/scratch/tree/master/beanish[ベアン人に関する資料 ]
を6枚コミットした

== 2014-02-05

https://github.com/pasberth/scratch/tree/master/beanish[ベアン人に関する資料 ]
を6枚コミットした

== 2014-02-06

https://github.com/pasberth/scratch/tree/master/beanish[ベアン人に関する資料 ]
を3枚コミットした

== 2014-02-07

.. raw:: html

    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
    <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
    <blockquote class="twitter-tweet" lang="ja"><p>ハル子 <a href="http://t.co/NSwGzAb3hu">pic.twitter.com/NSwGzAb3hu</a></p>&mdash; パスベルス (@pasberth) <a href="https://twitter.com/pasberth/statuses/431770169120002048">2014, 2月 7</a></blockquote>


== 2014-02-08

雪で遊んだ．
http://practical-scheme.net/trans/hundred-j.html[百年の言語 --- The Hundred-Year Language ]
を読んだ．

== 2014-02-09

http://melpon.org/blog/haskell-import-qualified[Haskellでのimportの使い方 ]
を読んだ．

== 2014-02-10

http://manticore-wiki.cs.uchicago.edu/index.php/Move_pattern_matching_into_CPS[Move pattern matching into CPS ]
を読んだ．

== 2014-02-11

.. raw:: html

    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
    <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
    <blockquote class="twitter-tweet" lang="ja"><p><a href="http://t.co/zRMTl4iTSJ">http://t.co/zRMTl4iTSJ</a> ルーフェ</p>&mdash; パスベルス (@pasberth) <a href="https://twitter.com/pasberth/statuses/433232028239028224">2014, 2月 11</a></blockquote>

* http://practical-scheme.net/docs/cont-j.html[なんでも継続 ]
* http://blog.practical-scheme.net/shiro?20120122-origin-of-continuations[継続の起源  ]
* http://kreisel.fam.cx/webmaster/clog/img/www.ice.nuie.nagoya-u.ac.jp/~h003149b/lang/actor/actor.html[SchemeとActor理論  ]
* http://www.cs.is.noda.tus.ac.jp/~mune/oop.bak/node9.html[並列オブジェクト指向 ]
を読んだ．

== 2014-02-12

* http://www.haskell.org/haskellwiki/GHC/Type_families[GHC/Type families ]
* http://www.haskell.org/ghc/docs/latest/html/users_guide/type-families.html[7.7. Type families ]
* http://faithandbrave.hateblo.jp/entry/20120106/1325832431[Type Families ]
を読んだ．

== 2014-02-13

.. raw:: html

    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
    <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

.. raw:: html

    <blockquote class="twitter-tweet" lang="ja"><p><a href="http://t.co/kHogyGv6JW">http://t.co/kHogyGv6JW</a> オリキャラデザイン</p>&mdash; パスベルス (@pasberth) <a href="https://twitter.com/pasberth/statuses/433983993663324161">2014, 2月 13</a></blockquote>


== 2014-02-14

.. raw:: html

    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
    <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

.. raw:: html

    <blockquote class="twitter-tweet" lang="ja"><p><a href="http://t.co/VMYehB3qha">http://t.co/VMYehB3qha</a> キャラデザ中です</p>&mdash; パスベルス (@pasberth) <a href="https://twitter.com/pasberth/statuses/434304743993643009">2014, 2月 14</a></blockquote>


== 2014-02-15

ファンタジーの設定を進めるなどした。
詳しくはコミットログを見て。

.. https://github.com/pasberth/scratch/compare/3a34b5899cd9211f25014382dcc9d43465800bb8...89d2a90ff6402c60f5236dc5abe3b9ca722c91db[進捗 ]

== 2014-02-16

ファンタジーの設定を進めるなどした。
詳しくはコミットログを見て。

.. https://github.com/pasberth/scratch/compare/de26ec87aaf722510be7a75d96798e713d09bc3b...d1fc02cff17b7f77b4b3797acdddea1c4522bbe9[進捗 ]

== 2014-02-17

読んだ:

* http://komoriyuichi.web.fc2.com/symposium/lambda-rho5.pdf[λρ-calculus ]
* http://pllab.is.ocha.ac.jp/zemi_8.html[「FelleisenのCオペレータ」 ]
* https://www.jstage.jst.go.jp/article/jssst/20/3/20_285/_pdf[λμ計算のモデルについて ]

読みたい:

* http://www.seas.upenn.edu/~sweirich/talks/GADT.pdf[GADT.pdf ]
* http://www.cl.cam.ac.uk/~tgg22/publications/popl90.pdf[A Formulae-as-Types Notion of Control ]
* http://pllab.is.ocha.ac.jp/~asai/jpapers/ppl/ueda10.pdf[型付き対称λ計算と古典論理 ]

== 2014-02-18

ファンタジーの設定を進めるなどした。
詳しくはコミットログを見て。

.. https://github.com/pasberth/scratch/compare/b4ac4576c62ec1c5746508a3323ce463d76fbef7...e7dcde8391dc805b8e19d452f6e6cca90d090935[進捗 ]

== 2014-02-19

読んだ:

* http://web.yl.is.s.u-tokyo.ac.jp/kobalab/kadai99/picalc.html[π-calculus 超入門 ]

ファンタジーの設定を進めるなどした。
詳しくはコミットログを見て。


== 2014-02-20

読んだ:


* http://ja.wikibooks.org/wiki/Haskell/Denotational_semantics#.E6.AD.A3.E6.A0.BC.E3.81.A8.E9.9D.9E.E6.AD.A3.E6.A0.BC.E3.81.AE.E6.84.8F.E5.91.B3[正格と非正格の意味 - Haskell/Denotational semantics ]
* http://itpro.nikkeibp.co.jp/article/COLUMN/20070305/263828/?ST=ittrend[本物のプログラマはHaskellを使う 第8回　遅延評価の仕組み ]
* http://itpro.nikkeibp.co.jp/article/COLUMN/20070403/267180/?ST=ittrend[本物のプログラマはHaskellを使う 第9回　Haskellはなぜ遅いと思われているのか ]
* http://d.hatena.ne.jp/mkotha/20110509/1304947182[Stricter Haskell ]

== 2014-02-21

.. https://github.com/pasberth/scratch/compare/0af39486178c4d16791f3d90b8244fa699d25ab0...ba192d51672d95f01550a43c94122b66302e1ed9[進捗 ]

ファンタジーの設定を進めるなどした。
詳しくはコミットログを見て。

https://github.com/pasberth/scratch/blob/0af39486178c4d16791f3d90b8244fa699d25ab0/characters/luna.png[ルーナの画像 ]
を描いたり。

== 2014-02-22

ファンタジーの設定を進めるなどした。
詳しくはコミットログを見て。

.. https://github.com/pasberth/scratch/compare/35c9ad13ed570576e0a48e3dcfb9106a5281e5ee...e4c058f30b575257b2cab186623d703d7959974d[進捗 ]

== 2014-02-23

ファンタジーの設定を進めるなどした。
詳しくはコミットログを見て。

.. https://github.com/pasberth/scratch/compare/e4c058f30b575257b2cab186623d703d7959974d...3a795cd9a2c460a9723f2bc55130f057867833b2[進捗 ] 

あと https://github.com/pasberth/chocochips.js[chocochips.js ] に
do記法を実装したりした。

== 2014-02-24

ファンタジーの設定を進めるなどした。
詳しくはコミットログを見て。


== 2014-02-25

ファンタジーの設定を進めるなどした。
詳しくはコミットログを見て。


== 2014-02-26

ファンタジーの設定を進めるなどした。
詳しくはコミットログを見て。

読んだ:

* http://minadukinaduki.web.fc2.com/sara1.htm[砂漠の巨人　上 ] 

== 2014-02-27

ファンタジーの設定を進めるなどした。
詳しくはコミットログを見て。

== 2014-02-28

ファンタジーの設定を進めるなどした。
詳しくはコミットログを見て。

読んだ:

* http://minadukinaduki.web.fc2.com/sara4.htm[砂漠の巨人　中 ]

== 2014-03-01

ファンタジーの設定を進めるなどした。
詳しくはコミットログを見て。

読んだ:

* http://minadukinaduki.web.fc2.com/sara6.htm[砂漠の巨人　下 ]

== 2014-03-02

AsciiDoc 神っつった


== 2014-03-03

SVG でフォントとかつくった

== 2014-03-04

http://pasberth.github.io/Ludwenics/magical/LudwenicFontExample.html とかつくった

== 2014-03-05

Inkscape でアレコレした

== 2014-03-06

https://github.com/pasberth/fontconv つくった

http://coq.io/ ヤバ

== 2014-03-07

ふたりのハードプロブレム読んだ

== 2014-03-08

ファンタジーの設定を進めるなどした。
詳しくはコミットログを見て。

== 2014-03-09

ファンタジーの設定を進めるなどした。
詳しくはコミットログを見て。

== 2014-03-10

ファンタジーの設定を進めるなどした。
詳しくはコミットログを見て。

http://rubygems.org/gems/asciidoctor-html5ruby つくった。

== 2014-03-11

死の世界からの放浪者という小説をアレして
アレした。 Asciidoctor の拡張にちょっと詳しくなった。

== 2014-03-12

死の世界からの放浪者という小説をアレして
アレした。

http://www.eps1.comlink.ne.jp/~mayus/milkhist.html[牛乳の歴史] 読んだ

== 2014-03-13

死の世界からの放浪者という小説をアレして
アレした。

== 2014-03-14

死の世界からの放浪者という小説をアレして
アレした。 map.svg をつくった。途中…

== 2014-03-15

ねぎまと http://ncode.syosetu.com/n9824bv/[真っ白な檻の中で、永遠に夏の夢を見ていたい。]
を読んだ

== 2014-03-16

灼ける石という小説を書いていた

== 2014-03-17

アルスマイアという小説を書いていた

== 2014-03-18

アルスマイアという小説を書いていた

== 2014-03-19

アルスマイアという小説を書いていた

== 2014-03-20

アルスマイアという小説を書いていた

== 2014-03-21

アルスマイアという小説を書いていた

いろいろ

== 2014-03-22

ログラインという言葉を知る

== 2014-03-23

アルスマイアという小説を書いていた

くどい表現をひたすら削ったりしてた。

アルスマイアの筋が悪かったので書き直すことにする

== 2014-03-24

magit, woman, term+,
helm, auto-complete, quickrun, paredit,
undo-tree, proof-general

読んだ:

* http://qiita.com/szktty/items/05cb2b754c88fbacc274[OCaml の記号あれこれ]
* http://d.hatena.ne.jp/osiire/20090510/1241957550[多相バリアントを使いこなそう(1)]
* http://d.hatena.ne.jp/osiire/20090516[多相バリアントを使いこなそう(4)]

== 2014-03-25

http://za.toypark.in/html/2010/02-24.html
http://affy.blogspot.jp/p5be/ch17.htm