= Asciidoctorを使おう！

== Asciidoctor?

Asciidoctor とは軽量マークアップ言語のひとつで、
HTML に変換できます。 Markdown, reStructuredText と似たような
用途で使うことができます。

処理系として http://asciidoc.org/[AsciiDoc] <<1>> や
http://asciidoctor.org/[Asciidoctor] <<2>> などがあります。
http://asciidoctor.org/docs/user-manual/#asciidoctor-vs-asciidoc[AsciiDoc と Asciidoctor の比較]
<<3>> もありますが、よくわからない場合は、 AsciiDoc は Python で実装されて実装されていて、
Asciidoctor は Ruby で実装されているということで、宗教的な理由で
使う方を選ぶとよいでしょう。なお、このブログは AsciiDoc は扱わず、
処理系として Asciidoctor を使うことを前提としています。

このブログは主に Asciidoctor の布教を目的としています。
このブログ自体も Asciidoctor でつくられています。
フフフ…怖いか？　実際に Asciidoctor を使うときは、
http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoc Syntax Quick Reference] <<4>> や
http://asciidoctor.org/docs/user-manual/[Asciidoctor User Manual] <<5>> をよく読むべきでしょう。

== Asciidoctorの使いどころ

Qiita やはてなブログでは Markdown を使って記事を書くことができますよね。
また、 GitHub の README もよく Markdown を使って書かれます。
あるいは、スライドが Markdown で書かれることもあります。

残念ながら Qiita などでは原理的に Asciidoctor を使って記事を書くことは
できないでしょう。それに仮に使えても、それが良い選択であることには
ならないと思います。

なぜなら、 Qiita で書く記事には必要とされないような
たくさんの機能が Asciidoctor にはあるからです。
もし Qiita で記事を書くときに Asciidoctor を使えても、
その機能のほとんどは腐ってしまうでしょう。 Markdown で書くのが
ちょうどいいと思います。

では、 Asciidoctor はどういうときに使うのだろう？
Asciidoctor は、ちょうど HTML を出力する LaTeX というような、
LaTeX と Markdown の中間のようなツールだと思います。
つまり、キレイなウェブページを書きたいけど、
HTML は書きたくない。そういう場合に使うといいと思います。

== Installation

asciidoctor は http://rubygems.org[RubyGems] にありますので、 +gem+ コマンドで
インストールできます。

[listing]
gem install asciidoctor

== Hello world

まずは hello world を試してみましょう。

.hello.adoc
----
include::hello.adoc[]
----

コンパイルするには、次のようなコマンドを入力します。

[listing]
asciidoctor hello.adoc

このコードをコンパイルすると、次のような HTML になるはずです。

[listing]
<p>hello world</p>

これで、ひとまず ``hello world'' と表示する
だけの HTML がつくられて、 +hello.html+ という名前で
保存されるはずです。

== AsciiDoc の概観

まずは AsciiDoc Syntax Quick Reference <<4>>
に載っている内容をザッと見てみましょう。くわしくはそのページを
読んでください。

http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#paragraphs
の内容です。

*パラグラフ* 単にテキストを書くと、それはパラグラフになります。

.paragraph.adoc
----
include::paragraph.adoc[]
----

*リテラル* パラグラフの先頭の文字が空白の場合は、リテラルになります。

.literal.adoc
----
include::literal.adoc[]
----

*改行* 行末に +++ という記号をおくとパラグラフ中で改行できます

.linebreak.adoc
----
include::linebreak.adoc[]
----

斜体、太字、等幅のサンプルです。
ネストもできますが、アンダースコアの内側に
アスタリスクやプラスサインを持ってくると
期待したようにいかない場合があります。

|===
|AsciiDoc|View

|`_hoge_`|_hoge_
|`__hoge__`|__hoge__
|`*hoge*`|*hoge*
|`**hoge**`|**hoge**
|`+hoge+`|+hoge+
|`++hoge++`|++hoge++

|`*_hoge_*`|*_hoge_*
|`_*hoge*_`|_*hoge*_
|`+*hoge*+`|+*hoge*+
|`*+hoge+*`|*+hoge+*
|`+_hoge_+`|+_hoge_+
|`_+hoge+_`|_+hoge+_

|`+*_hoge_*+`|+*_hoge_*+
|`_*+hoge+*_`|_*+hoge+*_
|`+_*hoge*_+`|+_*hoge*_+
|`_+*hoge*+_`|_+*hoge*+_
|`*+_hoge_+*`|*+_hoge_+*
|`*_+hoge+_*`|*_+hoge+_*
|===

Markdown や reST を使っていて
とにかく欲しい欲しいと思っていた
添字です！　これがあるというだけで
AsciiDoc を使う理由になりますわ＾〜

|===
|AsciiDoc|View

|`hoge^fuga^`|hoge^fuga^
|`hoge~fuga~`|hoge~fuga~
|===

== CSS を使う

これはほんとに見事だと思う仕様です。 AsciiDoc は
CSS を使ってスタイルを拡張できるようになっています。

インラインの場合は `[class]#text...#` のようにします。

.custom-styling.adoc
----
include::custom-styling.adoc[]
----

このコードをコンパイルすると、次のような HTML になるはずです。

[listing]
<span class="hoge fuga piyo">custom styling</span>

== MathJax を使う

朗報です！　asciidoctor 1.5.preview.1 から、
MathJax が使えるようになりました。


.mathjax.adoc
----
include::mathjax.adoc[]
----



== 参考文献

[bibliography]
- [[[1]]] http://asciidoc.org/[AsciiDoc]
- [[[2]]] http://asciidoctor.org/[Asciidoctor]
- [[[3]]] http://asciidoctor.org/docs/user-manual/#asciidoctor-vs-asciidoc[6. Appendix A: Comparison of Asciidoctor and AsciiDoc Features]
- [[[4]]] http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoc Syntax Quick Reference]
- [[[5]]] http://asciidoctor.org/docs/user-manual/[Asciidoctor User Manual]
